"""PDF report generation for Suits AI using fpdf2.

Supports multiple export types: negotiation_brief, risk_summary,
clause_report, and full_bundle.
"""

from __future__ import annotations

from typing import Literal

from fpdf import FPDF

from logging_config import get_logger
from models import (
    AnalysisResult,
    BenchmarkResult,
    ClassificationResult,
    Clause,
    CriticalIssue,
    DocumentMetadata,
    RiskResult,
)

logger = get_logger("reports.negotiation_brief")

ExportType = Literal["negotiation_brief", "risk_summary", "clause_report", "full_bundle"]

# ── Risk-level colours ───────────────────────────────────────────────────────
_RISK_COLORS: dict[str, tuple[int, int, int]] = {
    "GREEN": (34, 197, 94),      # #22c55e
    "YELLOW": (234, 179, 8),     # #eab308
    "RED": (239, 68, 68),        # #ef4444
}

_RISK_LEVEL_ORDER = {"LOW_RISK": 0, "MODERATE_RISK": 1, "HIGH_RISK": 2, "CRITICAL_RISK": 3}

_EXPORT_TITLES: dict[str, str] = {
    "negotiation_brief": "NEGOTIATION BRIEF",
    "risk_summary": "RISK SUMMARY",
    "clause_report": "CLAUSE REPORT",
    "full_bundle": "FULL ANALYSIS BUNDLE",
}


def _safe(text: str, max_len: int = 0) -> str:
    """Sanitise text for fpdf2 (replace unsupported chars, optionally truncate)."""
    # Strip control characters that break fpdf2 layout
    cleaned = text.replace("\r", "").replace("\t", "    ")
    cleaned = cleaned.encode("latin-1", errors="replace").decode("latin-1")
    if max_len and len(cleaned) > max_len:
        return cleaned[: max_len - 3] + "..."
    return cleaned


class _LegalPDF(FPDF):
    """FPDF subclass with branded header/footer."""

    def __init__(self, export_title: str, doc_info: str) -> None:
        super().__init__(orientation="P", unit="mm", format="A4")
        self._export_title = export_title
        self._doc_info = doc_info
        self.set_auto_page_break(auto=True, margin=20)

    def header(self) -> None:  # noqa: D401
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(60, 60, 60)
        self.cell(0, 6, f"SUITS AI  |  {self._export_title}", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 8)
        self.set_text_color(120, 120, 120)
        self.cell(0, 4, self._doc_info, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y() + 1, 200, self.get_y() + 1)
        self.ln(4)

    def footer(self) -> None:  # noqa: D401
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(160, 160, 160)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}  |  Generated by Suits AI", align="C")


class NegotiationBriefGenerator:
    """Generates professional PDF reports from analysis results."""

    # ── Public API ───────────────────────────────────────────────────────

    def generate(
        self,
        analysis: AnalysisResult,
        metadata: DocumentMetadata,
        export_type: str = "negotiation_brief",
    ) -> bytes:
        """Build a PDF and return it as raw bytes."""
        if export_type not in _EXPORT_TITLES:
            export_type = "negotiation_brief"

        title = _EXPORT_TITLES[export_type]
        doc_info = f"Document: {metadata.filename}  |  ID: {metadata.document_id[:12]}..."

        pdf = _LegalPDF(export_title=title, doc_info=doc_info)
        pdf.alias_nb_pages()
        pdf.add_page()

        # Build lookup maps for convenience
        risk_map: dict[int, RiskResult] = {r.clause_id: r for r in analysis.risks}
        class_map: dict[int, ClassificationResult] = {
            c.clause_id: c for c in analysis.classifications
        }
        bench_map: dict[int, BenchmarkResult] = {
            b.clause_id: b for b in analysis.benchmarks
        }

        section_map = {
            "negotiation_brief": [
                ("executive_summary", lambda: self._section_executive_summary(pdf, analysis)),
                ("critical_issues", lambda: self._section_critical_issues(pdf, analysis)),
                ("missing_protections", lambda: self._section_missing_protections(pdf, analysis)),
                ("positive_aspects", lambda: self._section_positive_aspects(pdf, analysis)),
                ("negotiation_checklist", lambda: self._section_negotiation_checklist(pdf, analysis)),
            ],
            "risk_summary": [
                ("executive_summary", lambda: self._section_executive_summary(pdf, analysis)),
                ("risk_score", lambda: self._section_risk_score(pdf, analysis)),
                ("critical_issues", lambda: self._section_critical_issues(pdf, analysis)),
                ("missing_protections", lambda: self._section_missing_protections(pdf, analysis)),
            ],
            "clause_report": [
                ("clause_table", lambda: self._section_clause_table(pdf, analysis, class_map, risk_map, bench_map)),
            ],
            "full_bundle": [
                ("executive_summary", lambda: self._section_executive_summary(pdf, analysis)),
                ("risk_score", lambda: self._section_risk_score(pdf, analysis)),
                ("critical_issues", lambda: self._section_critical_issues(pdf, analysis)),
                ("clause_table", lambda: self._section_clause_table(pdf, analysis, class_map, risk_map, bench_map)),
                ("missing_protections", lambda: self._section_missing_protections(pdf, analysis)),
                ("positive_aspects", lambda: self._section_positive_aspects(pdf, analysis)),
                ("negotiation_checklist", lambda: self._section_negotiation_checklist(pdf, analysis)),
            ],
        }

        for section_name, render_fn in section_map[export_type]:
            try:
                render_fn()
            except Exception as exc:
                logger.warning(
                    f"PDF section {section_name} failed: {exc}",
                    extra={"agent": "reports", "status": "warning"},
                )
                # Render a fallback note and continue
                pdf.set_x(pdf.l_margin)
                pdf.set_font("Helvetica", "I", 9)
                pdf.set_text_color(180, 0, 0)
                pdf.multi_cell(0, 5, f"[Section '{section_name}' could not be rendered]")
                pdf.ln(2)

        logger.info(
            "PDF report generated",
            extra={"agent": "reports", "status": "success"},
        )

        return bytes(pdf.output())

    # ── Section builders ─────────────────────────────────────────────────

    def _heading(self, pdf: _LegalPDF, text: str, level: int = 1) -> None:
        size = {1: 14, 2: 12, 3: 10}.get(level, 10)
        pdf.ln(3)
        pdf.set_font("Helvetica", "B", size)
        pdf.set_text_color(30, 30, 30)
        pdf.cell(0, 8, _safe(text), new_x="LMARGIN", new_y="NEXT")
        if level == 1:
            pdf.set_draw_color(50, 50, 50)
            pdf.line(10, pdf.get_y(), 200, pdf.get_y())
            pdf.ln(2)
        pdf.ln(1)

    def _body(self, pdf: _LegalPDF, text: str, max_len: int = 2000) -> None:
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        # Reset x to left margin to avoid "not enough horizontal space" errors
        pdf.set_x(pdf.l_margin)
        pdf.multi_cell(0, 5, _safe(text, max_len=max_len))
        pdf.ln(1)

    def _risk_badge(self, pdf: _LegalPDF, level: str) -> None:
        r, g, b = _RISK_COLORS.get(level, (120, 120, 120))
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(22, 5, f" {level} ", fill=True)
        pdf.set_text_color(50, 50, 50)

    # ── Sections ─────────────────────────────────────────────────────────

    def _section_executive_summary(self, pdf: _LegalPDF, analysis: AnalysisResult) -> None:
        self._heading(pdf, "Executive Summary")
        advisory = analysis.advisory
        if advisory and advisory.executive_summary:
            self._body(pdf, advisory.executive_summary)
        else:
            self._body(pdf, "No executive summary available.")

        if advisory and advisory.document_summary:
            ds = advisory.document_summary
            details: list[str] = []
            if ds.document_type:
                details.append(f"Document Type: {ds.document_type}")
            if ds.parties:
                details.append(f"Parties: {', '.join(ds.parties)}")
            if ds.effective_date:
                details.append(f"Effective Date: {ds.effective_date}")
            if ds.duration:
                details.append(f"Duration: {ds.duration}")
            if ds.total_clauses_analyzed:
                details.append(f"Total Clauses Analyzed: {ds.total_clauses_analyzed}")
            if ds.key_financial_terms:
                details.append(f"Key Financial Terms: {ds.key_financial_terms}")
            if details:
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(80, 80, 80)
                for d in details:
                    pdf.cell(0, 5, _safe(f"  - {d}"), new_x="LMARGIN", new_y="NEXT")
                pdf.ln(2)

    def _section_risk_score(self, pdf: _LegalPDF, analysis: AnalysisResult) -> None:
        self._heading(pdf, "Overall Risk Assessment")
        advisory = analysis.advisory
        if advisory and advisory.overall_risk_assessment:
            ora = advisory.overall_risk_assessment
            pdf.set_font("Helvetica", "B", 20)
            # Choose colour based on risk level
            level_color = {
                "LOW_RISK": (34, 197, 94),
                "MODERATE_RISK": (234, 179, 8),
                "HIGH_RISK": (239, 68, 68),
                "CRITICAL_RISK": (180, 0, 0),
            }
            r, g, b = level_color.get(ora.level, (100, 100, 100))
            pdf.set_text_color(r, g, b)
            pdf.cell(0, 12, f"{ora.score}/100  -  {ora.level.replace('_', ' ')}", new_x="LMARGIN", new_y="NEXT")

            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(50, 50, 50)
            pdf.cell(0, 8, f"Verdict: {ora.verdict.replace('_', ' ')}", new_x="LMARGIN", new_y="NEXT")

            if ora.verdict_reasoning:
                self._body(pdf, ora.verdict_reasoning)
            pdf.ln(2)
        else:
            self._body(pdf, "No overall risk assessment available.")

    def _section_critical_issues(self, pdf: _LegalPDF, analysis: AnalysisResult) -> None:
        self._heading(pdf, "Critical Issues")
        advisory = analysis.advisory
        issues = advisory.critical_issues if advisory else []

        if not issues:
            self._body(pdf, "No critical issues identified.")
            return

        # Table header (total 186mm, leaving 4mm buffer on 190mm usable width)
        col_widths = [10, 18, 22, 136]  # Rank, Clause, Risk, Issue
        headers = ["Rank", "Clause", "Risk", "Issue"]
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_text_color(30, 30, 30)
        for i, header in enumerate(headers):
            pdf.cell(col_widths[i], 6, header, border=1, fill=True)
        pdf.ln()

        # Table rows
        risk_map: dict[int, RiskResult] = {r.clause_id: r for r in analysis.risks}
        pdf.set_font("Helvetica", "", 8)
        for issue in sorted(issues, key=lambda i: i.priority):
            risk = risk_map.get(issue.clause_id)
            risk_score_str = str(risk.risk_score) if risk else "-"
            risk_level = risk.risk_level if risk else "GREEN"

            pdf.set_text_color(50, 50, 50)
            pdf.cell(col_widths[0], 6, str(issue.priority), border=1)
            pdf.cell(col_widths[1], 6, f"C{issue.clause_id}", border=1)

            # Color-coded risk cell
            r, g, b = _RISK_COLORS.get(risk_level, (120, 120, 120))
            pdf.set_fill_color(r, g, b)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(col_widths[2], 6, f"{risk_score_str} ({risk_level})", border=1, fill=True)
            pdf.set_text_color(50, 50, 50)

            pdf.cell(col_widths[3], 6, _safe(issue.issue_title, 80), border=1)
            pdf.ln()

        pdf.ln(3)

        # Detailed breakdown per issue
        for issue in sorted(issues, key=lambda i: i.priority):
            self._heading(pdf, f"#{issue.priority} — {issue.issue_title}", level=3)
            if issue.issue_description:
                self._body(pdf, f"Description: {issue.issue_description}")
            if issue.impact:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(180, 0, 0)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Impact:", new_x="LMARGIN", new_y="NEXT")
                self._body(pdf, issue.impact)
            if issue.recommended_action:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(0, 100, 0)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Recommended Action:", new_x="LMARGIN", new_y="NEXT")
                self._body(pdf, issue.recommended_action)
            if issue.suggested_counter_language:
                pdf.set_font("Helvetica", "BI", 9)
                pdf.set_text_color(30, 30, 120)
                pdf.set_x(pdf.l_margin)
                pdf.cell(0, 5, "Suggested Counter-Language:", new_x="LMARGIN", new_y="NEXT")
                self._body(pdf, issue.suggested_counter_language)

    def _section_missing_protections(self, pdf: _LegalPDF, analysis: AnalysisResult) -> None:
        self._heading(pdf, "Missing Protections")
        advisory = analysis.advisory
        missing = advisory.missing_clauses if advisory else []

        if not missing:
            self._body(pdf, "No missing standard protections identified.")
            return

        for idx, m in enumerate(missing, 1):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(180, 0, 0)
            pdf.set_x(pdf.l_margin)
            pdf.cell(0, 5, _safe(f"{idx}. {m.clause_type}", max_len=100), new_x="LMARGIN", new_y="NEXT")
            pdf.set_text_color(50, 50, 50)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, _safe(f"Why important: {m.why_important}", max_len=500))
            if m.suggested_language:
                pdf.set_font("Helvetica", "I", 8)
                pdf.set_x(pdf.l_margin)
                pdf.multi_cell(0, 4, _safe(f"Suggested: {m.suggested_language}", max_len=500))
            pdf.ln(1)

    def _section_positive_aspects(self, pdf: _LegalPDF, analysis: AnalysisResult) -> None:
        self._heading(pdf, "Positive Aspects")
        advisory = analysis.advisory
        positives = advisory.positive_aspects if advisory else []

        if not positives:
            self._body(pdf, "No positive aspects highlighted.")
            return

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(0, 120, 0)
        for p in positives:
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, _safe(f"+ [Clause {p.clause_id}] {p.description}", max_len=300))
        pdf.set_text_color(50, 50, 50)
        pdf.ln(2)

    def _section_negotiation_checklist(self, pdf: _LegalPDF, analysis: AnalysisResult) -> None:
        self._heading(pdf, "Negotiation Checklist")
        advisory = analysis.advisory
        priorities = advisory.negotiation_priority_order if advisory else []

        if not priorities:
            self._body(pdf, "No negotiation priorities available.")
            return

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(50, 50, 50)
        for idx, item in enumerate(priorities, 1):
            pdf.set_x(pdf.l_margin)
            pdf.multi_cell(0, 5, _safe(f"[ ] {idx}. {item}", max_len=300))
        pdf.ln(2)

    def _section_clause_table(
        self,
        pdf: _LegalPDF,
        analysis: AnalysisResult,
        class_map: dict[int, ClassificationResult],
        risk_map: dict[int, RiskResult],
        bench_map: dict[int, BenchmarkResult],
    ) -> None:
        self._heading(pdf, "Clause-by-Clause Analysis")

        if not analysis.clauses:
            self._body(pdf, "No clauses available.")
            return

        # Table header (total 186mm, leaving 4mm buffer on 190mm usable width)
        col_widths = [10, 28, 26, 18, 40, 64]  # ID, Category, Deviation, Risk, Title, Summary
        headers = ["ID", "Category", "Deviation", "Risk", "Title", "Summary"]
        pdf.set_font("Helvetica", "B", 7)
        pdf.set_fill_color(240, 240, 240)
        pdf.set_text_color(30, 30, 30)
        for i, h in enumerate(headers):
            pdf.cell(col_widths[i], 6, h, border=1, fill=True)
        pdf.ln()

        # Build simplification map for summaries
        simp_map = {s.clause_id: s.simplified_text for s in analysis.simplifications}

        pdf.set_font("Helvetica", "", 7)
        for clause in analysis.clauses:
            cid = clause.clause_id
            cat = class_map.get(cid)
            risk = risk_map.get(cid)
            bench = bench_map.get(cid)
            summary = simp_map.get(cid, "")

            category = cat.category if cat else "-"
            deviation = bench.deviation_level.replace("_", " ") if bench else "-"
            risk_level = risk.risk_level if risk else "GREEN"

            pdf.set_text_color(50, 50, 50)
            pdf.cell(col_widths[0], 6, str(cid), border=1)
            pdf.cell(col_widths[1], 6, _safe(category, 18), border=1)
            pdf.cell(col_widths[2], 6, _safe(deviation, 16), border=1)

            # Colored risk cell
            r, g, b = _RISK_COLORS.get(risk_level, (120, 120, 120))
            pdf.set_fill_color(r, g, b)
            pdf.set_text_color(255, 255, 255)
            pdf.cell(col_widths[3], 6, risk_level, border=1, fill=True)
            pdf.set_text_color(50, 50, 50)

            pdf.cell(col_widths[4], 6, _safe(clause.title, 24), border=1)
            pdf.cell(col_widths[5], 6, _safe(summary, 38), border=1)
            pdf.ln()

        pdf.ln(2)
